package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String nome;
     private Float salario;
     private String cargaHoraria;
     private Set funcionarios = new HashSet(0);

    public Cargo() {
    }

    public Cargo(String nome, Float salario, String cargaHoraria, Set funcionarios) {
       this.nome = nome;
       this.salario = salario;
       this.cargaHoraria = cargaHoraria;
       this.funcionarios = funcionarios;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public String getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(String cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


