package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Eventos generated by hbm2java
 */
public class Eventos  implements java.io.Serializable {


     private Integer idEventos;
     private Endereco endereco;
     private String nomeEvento;
     private String dataInicio;
     private String dataFinal;
     private Set stands = new HashSet(0);

    public Eventos() {
    }

	
    public Eventos(Endereco endereco) {
        this.endereco = endereco;
    }
    public Eventos(Endereco endereco, String nomeEvento, String dataInicio, String dataFinal, Set stands) {
       this.endereco = endereco;
       this.nomeEvento = nomeEvento;
       this.dataInicio = dataInicio;
       this.dataFinal = dataFinal;
       this.stands = stands;
    }
   
    public Integer getIdEventos() {
        return this.idEventos;
    }
    
    public void setIdEventos(Integer idEventos) {
        this.idEventos = idEventos;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNomeEvento() {
        return this.nomeEvento;
    }
    
    public void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }
    public String getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }
    public String getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(String dataFinal) {
        this.dataFinal = dataFinal;
    }
    public Set getStands() {
        return this.stands;
    }
    
    public void setStands(Set stands) {
        this.stands = stands;
    }




}


