package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idfuncionario;
     private Cargo cargo;
     private Endereco endereco;
     private String cpf;
     private String rg;
     private String nome;
     private String sexo;
     private String cnh;

    public Funcionario() {
    }

	
    public Funcionario(Cargo cargo, Endereco endereco, String cpf) {
        this.cargo = cargo;
        this.endereco = endereco;
        this.cpf = cpf;
    }
    public Funcionario(Cargo cargo, Endereco endereco, String cpf, String rg, String nome, String sexo, String cnh) {
       this.cargo = cargo;
       this.endereco = endereco;
       this.cpf = cpf;
       this.rg = rg;
       this.nome = nome;
       this.sexo = sexo;
       this.cnh = cnh;
    }
   
    public Integer getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(Integer idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCnh() {
        return this.cnh;
    }
    
    public void setCnh(String cnh) {
        this.cnh = cnh;
    }




}


