package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer idProdutos;
     private String produtoNome;
     private String produtoCor;
     private String produtoTipo;
     private String produtoMarca;
     private Integer produtoQuantidade;
     private Set produtosUtilizadoses = new HashSet(0);

    public Produtos() {
    }

    public Produtos(String produtoNome, String produtoCor, String produtoTipo, String produtoMarca, Integer produtoQuantidade, Set produtosUtilizadoses) {
       this.produtoNome = produtoNome;
       this.produtoCor = produtoCor;
       this.produtoTipo = produtoTipo;
       this.produtoMarca = produtoMarca;
       this.produtoQuantidade = produtoQuantidade;
       this.produtosUtilizadoses = produtosUtilizadoses;
    }
   
    public Integer getIdProdutos() {
        return this.idProdutos;
    }
    
    public void setIdProdutos(Integer idProdutos) {
        this.idProdutos = idProdutos;
    }
    public String getProdutoNome() {
        return this.produtoNome;
    }
    
    public void setProdutoNome(String produtoNome) {
        this.produtoNome = produtoNome;
    }
    public String getProdutoCor() {
        return this.produtoCor;
    }
    
    public void setProdutoCor(String produtoCor) {
        this.produtoCor = produtoCor;
    }
    public String getProdutoTipo() {
        return this.produtoTipo;
    }
    
    public void setProdutoTipo(String produtoTipo) {
        this.produtoTipo = produtoTipo;
    }
    public String getProdutoMarca() {
        return this.produtoMarca;
    }
    
    public void setProdutoMarca(String produtoMarca) {
        this.produtoMarca = produtoMarca;
    }
    public Integer getProdutoQuantidade() {
        return this.produtoQuantidade;
    }
    
    public void setProdutoQuantidade(Integer produtoQuantidade) {
        this.produtoQuantidade = produtoQuantidade;
    }
    public Set getProdutosUtilizadoses() {
        return this.produtosUtilizadoses;
    }
    
    public void setProdutosUtilizadoses(Set produtosUtilizadoses) {
        this.produtosUtilizadoses = produtosUtilizadoses;
    }




}


