package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1



/**
 * ProdutosUtilizados generated by hbm2java
 */
public class ProdutosUtilizados  implements java.io.Serializable {


     private Integer idProdutosUtilizados;
     private Produtos produtos;
     private Stand stand;
     private String observacao;

    public ProdutosUtilizados() {
    }

	
    public ProdutosUtilizados(Produtos produtos, Stand stand) {
        this.produtos = produtos;
        this.stand = stand;
    }
    public ProdutosUtilizados(Produtos produtos, Stand stand, String observacao) {
       this.produtos = produtos;
       this.stand = stand;
       this.observacao = observacao;
    }
   
    public Integer getIdProdutosUtilizados() {
        return this.idProdutosUtilizados;
    }
    
    public void setIdProdutosUtilizados(Integer idProdutosUtilizados) {
        this.idProdutosUtilizados = idProdutosUtilizados;
    }
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }
    public Stand getStand() {
        return this.stand;
    }
    
    public void setStand(Stand stand) {
        this.stand = stand;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


