package entidade;
// Generated 21/11/2016 20:40:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stand generated by hbm2java
 */
public class Stand  implements java.io.Serializable {


     private Integer idStand;
     private Cliente cliente;
     private Eventos eventos;
     private String localizacao;
     private Float precoServico;
     private Set produtosUtilizadoses = new HashSet(0);

    public Stand() {
    }

	
    public Stand(Cliente cliente, Eventos eventos) {
        this.cliente = cliente;
        this.eventos = eventos;
    }
    public Stand(Cliente cliente, Eventos eventos, String localizacao, Float precoServico, Set produtosUtilizadoses) {
       this.cliente = cliente;
       this.eventos = eventos;
       this.localizacao = localizacao;
       this.precoServico = precoServico;
       this.produtosUtilizadoses = produtosUtilizadoses;
    }
   
    public Integer getIdStand() {
        return this.idStand;
    }
    
    public void setIdStand(Integer idStand) {
        this.idStand = idStand;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Eventos getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Eventos eventos) {
        this.eventos = eventos;
    }
    public String getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(String localizacao) {
        this.localizacao = localizacao;
    }
    public Float getPrecoServico() {
        return this.precoServico;
    }
    
    public void setPrecoServico(Float precoServico) {
        this.precoServico = precoServico;
    }
    public Set getProdutosUtilizadoses() {
        return this.produtosUtilizadoses;
    }
    
    public void setProdutosUtilizadoses(Set produtosUtilizadoses) {
        this.produtosUtilizadoses = produtosUtilizadoses;
    }




}


