/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import controle.ClienteDAO;
import controle.EnderecoDAO;
import entidade.Cliente;
import entidade.Endereco;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author bieuu
 */
public class Cadastro_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Cliente
     */
    public Cadastro_Cliente() {
        initComponents();
    }
    List<Cliente> vetorcliente = new ArrayList<>();
    Cliente cliente;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcnpj = new javax.swing.JLabel();
        lblcpf = new javax.swing.JLabel();
        lbltelefone = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtcpf = new javax.swing.JFormattedTextField();
        btnEnviar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtrazaosocial = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JFormattedTextField();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listbuscar = new javax.swing.JList<>();
        btnpessoajuridica = new javax.swing.JRadioButton();
        btnpessoafisica = new javax.swing.JRadioButton();
        lblogradouro = new javax.swing.JLabel();
        txtlogradouro = new javax.swing.JTextField();
        lbestado = new javax.swing.JLabel();
        lbcidade = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        lbcep = new javax.swing.JLabel();
        lbcomplemento = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        lbnumero = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        lbbairro = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        btnbuscarCep = new javax.swing.JButton();
        txtcep = new javax.swing.JFormattedTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 22, 263, 29);

        lblnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblnome.setText("Nome:");
        getContentPane().add(lblnome);
        lblnome.setBounds(0, 170, 59, 22);

        lblcnpj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcnpj.setText("CNPJ:");
        getContentPane().add(lblcnpj);
        lblcnpj.setBounds(0, 270, 50, 22);

        lblcpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcpf.setText("CPF:");
        getContentPane().add(lblcpf);
        lblcpf.setBounds(0, 210, 40, 22);

        lbltelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltelefone.setText("Telefone:");
        getContentPane().add(lbltelefone);
        lbltelefone.setBounds(0, 300, 84, 22);

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblemail.setText("Email:");
        getContentPane().add(lblemail);
        lblemail.setBounds(0, 330, 54, 22);

        txtnome.setEnabled(false);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome);
        txtnome.setBounds(60, 180, 202, 19);

        txttelefone.setEnabled(false);
        getContentPane().add(txttelefone);
        txttelefone.setBounds(80, 300, 178, 19);

        txtemail.setEnabled(false);
        getContentPane().add(txtemail);
        txtemail.setBounds(60, 330, 204, 24);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678595_Human.png"))); // NOI18N
        jButton1.setText("Cadastro CLiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678780_3d_box.png"))); // NOI18N
        jButton3.setText("Produtos");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678699_square-calendar.png"))); // NOI18N
        jButton4.setText("Agenda");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678573_Document.png"))); // NOI18N
        jButton5.setText("Pedidos");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678654_Technology_Mix_-_Final-16.png"))); // NOI18N
        jButton6.setText("Cadastro Funcionarios");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1474678836_architecture-interior-14.png"))); // NOI18N
        jButton2.setText("Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 660, 847, 49);

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setEnabled(false);
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpf);
        txtcpf.setBounds(40, 210, 216, 19);

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1476343190_sent.png"))); // NOI18N
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(0, 620, 69, 33);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1476343275_office-46.png"))); // NOI18N
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(170, 620, 66, 33);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1476343200_cross-24.png"))); // NOI18N
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar);
        btnFechar.setBounds(250, 620, 66, 33);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Endereço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 350, 110, 50);

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1476486939_pen-checkbox.png"))); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar);
        btneditar.setBounds(80, 620, 69, 33);

        btnPesquisar.setText("...");
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(270, 180, 32, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cod:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 73, 41, 22);
        getContentPane().add(txtcod);
        txtcod.setBounds(41, 77, 40, 19);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Razão Social:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 240, 116, 22);

        txtrazaosocial.setEnabled(false);
        getContentPane().add(txtrazaosocial);
        txtrazaosocial.setBounds(110, 240, 145, 19);

        try {
            txtcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcnpj.setEnabled(false);
        getContentPane().add(txtcnpj);
        txtcnpj.setBounds(60, 270, 200, 19);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(410, 80, 220, 30);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(640, 70, 80, 40);

        listbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listbuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listbuscar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 130, 300, 250);

        buttonGroup1.add(btnpessoajuridica);
        btnpessoajuridica.setText("Pessoa Juridica");
        btnpessoajuridica.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnpessoajuridicaComponentShown(evt);
            }
        });
        btnpessoajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpessoajuridicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpessoajuridica);
        btnpessoajuridica.setBounds(10, 130, 133, 23);

        buttonGroup1.add(btnpessoafisica);
        btnpessoafisica.setText("Pessoa Fisica");
        btnpessoafisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpessoafisicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpessoafisica);
        btnpessoafisica.setBounds(120, 130, 121, 23);

        lblogradouro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblogradouro.setText("Logradouro:");
        getContentPane().add(lblogradouro);
        lblogradouro.setBounds(0, 460, 110, 22);

        txtlogradouro.setEnabled(false);
        getContentPane().add(txtlogradouro);
        txtlogradouro.setBounds(100, 460, 200, 19);

        lbestado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbestado.setText("Estado:");
        getContentPane().add(lbestado);
        lbestado.setBounds(0, 490, 90, 22);

        lbcidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbcidade.setText("Cidade:");
        getContentPane().add(lbcidade);
        lbcidade.setBounds(0, 430, 67, 22);

        txtcidade.setEnabled(false);
        getContentPane().add(txtcidade);
        txtcidade.setBounds(60, 430, 210, 19);

        lbcep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbcep.setText("CEP:");
        getContentPane().add(lbcep);
        lbcep.setBounds(0, 400, 100, 22);

        lbcomplemento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbcomplemento.setText("Complemento:");
        getContentPane().add(lbcomplemento);
        lbcomplemento.setBounds(0, 550, 131, 22);

        txtcomplemento.setEnabled(false);
        getContentPane().add(txtcomplemento);
        txtcomplemento.setBounds(120, 550, 180, 19);

        lbnumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbnumero.setText("Numero:");
        getContentPane().add(lbnumero);
        lbnumero.setBounds(0, 580, 78, 22);

        txtnumero.setEnabled(false);
        getContentPane().add(txtnumero);
        txtnumero.setBounds(80, 580, 230, 19);

        lbbairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbbairro.setText("Bairro:");
        getContentPane().add(lbbairro);
        lbbairro.setBounds(0, 520, 60, 22);

        txtbairro.setEnabled(false);
        getContentPane().add(txtbairro);
        txtbairro.setBounds(60, 520, 240, 19);

        btnbuscarCep.setText("Buscar");
        btnbuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarCepActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscarCep);
        btnbuscarCep.setBounds(290, 400, 82, 25);

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setEnabled(false);
        getContentPane().add(txtcep);
        txtcep.setBounds(40, 400, 220, 19);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC ", "AL ", "AP ", "AM ", "BA ", "CE ", "DF ", "ES ", "MA ", "MT ", "MS ", "MG ", "PA ", "PB ", "PR ", "PE ", "PI ", "RJ ", "RN ", "RS ", "RO ", "RR ", "SC ", "SP ", "SE ", "TO" }));
        getContentPane().add(cbEstado);
        cbEstado.setBounds(60, 490, 230, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 130, 45, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF/CNPJ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 150, 71, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 170, 50, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Razão Social");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 190, 90, 17);

        jMenu3.setText("Atalhos");
        jMenu3.setToolTipText("");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed

    }//GEN-LAST:event_txtcpfActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        txtnome.setText("");
        txtcnpj.setText("");
        txtemail.setText("");
        txtcpf.setText("");
        txttelefone.setText("");
        txtcep.setText("");
        txtcidade.setText("");
        txtlogradouro.setText("");
        txtbairro.setText("");
        txtcomplemento.setText("");
        txtnumero.setText("");
        
        
       
       
        
        
        
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Cliente cli = new Cliente();
        cli.setNome(txtnome.getText());
        cli.setRazaoSocial(txtrazaosocial.getText());
        cli.setCnpjCpf(txtcnpj.getText());
        cli.setTelefone(txttelefone.getText());
        cli.setEmail(txtemail.getText());
        Endereco ender = new Endereco();
        ender.setCep(txtcep.getText());
        ender.setCidade(txtcidade.getText());
        ender.setLogradouro(txtlogradouro.getText());
        ender.setEstado(cbEstado.getSelectedItem().toString());
        ender.setBairro(txtbairro.getText());
        ender.setComplemento(txtcomplemento.getText());
        ender.setNumero(txtnumero.getText());

      String codigo = txtcod.getText();
        if (!codigo.isEmpty()){
            cli.setIdCliente(Integer.valueOf(codigo)); 
            
        EnderecoDAO edao = new EnderecoDAO();
        edao.salvar(ender);

        cli.setEndereco(ender);

        ClienteDAO cdao = new ClienteDAO();
        cdao.salvar(cli);

        txtnome.setEnabled(false);
        txtcnpj.setEnabled(false);
        txtcpf.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefone.setEnabled(false);
        txtcod.setEditable(false);
        txtrazaosocial.setEnabled(false);

        btneditar.setEnabled(false);
        btnEnviar.setEnabled(false);

        txtnome.setText("");
        txtcnpj.setText("");
        txtcpf.setText("");
        txtemail.setText("");
        txttelefone.setText("");
        txtcod.setText("");
        txtrazaosocial.setText("");
        txtnome.requestFocus();

        JOptionPane.showMessageDialog(null, "Enviado com Sucesso");
        
        
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
   
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        Cliente cli = new Cliente();
        cli.setNome(txtnome.getText());
        cli.setRazaoSocial(txtrazaosocial.getText());
        cli.setCnpjCpf(txtcnpj.getText());
        cli.setTelefone(txttelefone.getText());
        cli.setEmail(txtemail.getText());
        String codigo = txtcod.getText();
        cli.setIdCliente(Integer.valueOf(codigo));

//        Endereco ender = new Endereco();
        cli.getEndereco().setCep(txtcep.getText());
        cli.getEndereco().setCidade(txtcidade.getText());
        cli.getEndereco().setLogradouro(txtlogradouro.getText());
        cli.getEndereco().setEstado(cbEstado.getSelectedItem().toString());
        cli.getEndereco().setBairro(txtbairro.getText());
        cli.getEndereco().setComplemento(txtcomplemento.getText());
        cli.getEndereco().setNumero(txtnumero.getText());

        ClienteDAO cdao = new ClienteDAO();
        cdao.salvar(cli);

        txtnome.setEnabled(false);
        txtcnpj.setEnabled(false);
        txtcpf.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefone.setEnabled(false);
        txtcod.setEditable(false);
        txtrazaosocial.setEnabled(false);

        btneditar.setEnabled(false);
        btnEnviar.setEnabled(false);

        txtnome.setText("");
        txtcnpj.setText("");
        txtcpf.setText("");
        txtemail.setText("");
        txttelefone.setText("");
        txtcod.setText("");
        txtrazaosocial.setText("");
        txtnome.requestFocus();

        JOptionPane.showMessageDialog(null, "Enviado com Sucesso");
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnbuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarCepActionPerformed

    }//GEN-LAST:event_btnbuscarCepActionPerformed

    private void btnpessoajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpessoajuridicaActionPerformed

txtnome.setEnabled(false);
txtrazaosocial.setEnabled(true);
txtcnpj.setEnabled(true);
txttelefone.setEnabled(true);
txtemail.setEnabled(true);
txtcpf.setEnabled(false);
txtcep.setEnabled(true);
txtcidade.setEnabled(true);
txtlogradouro.setEnabled(true);
txtbairro.setEnabled(true);
txtcomplemento.setEnabled(true);
txtnumero.setEnabled(true);
btnEnviar.setEnabled(true);
btnLimpar.setEnabled(true);
            
        
    

    }//GEN-LAST:event_btnpessoajuridicaActionPerformed

    private void btnpessoajuridicaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnpessoajuridicaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpessoajuridicaComponentShown

    private void btnpessoafisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpessoafisicaActionPerformed
txtcpf.setEnabled(true);
btnEnviar.setEnabled(true);
btnLimpar.setEnabled(true);
txtnome.setEnabled(true);
txtrazaosocial.setEnabled(true);
txtcnpj.setEnabled(false);
txttelefone.setEnabled(true);
txtemail.setEnabled(true);

txtcep.setEnabled(true);
txtcidade.setEnabled(true);
txtlogradouro.setEnabled(true);
txtbairro.setEnabled(true);
txtcomplemento.setEnabled(true);
txtnumero.setEnabled(true);    }//GEN-LAST:event_btnpessoafisicaActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String texto = txtbuscar.getText();
        ClienteDAO cdao = new ClienteDAO();
        vetorcliente = cdao.buscacliente(texto);
        DefaultListModel modelo = new DefaultListModel();
        for (Cliente cliente : vetorcliente){
            modelo.addElement(cliente.getNome());
            modelo.addElement(cliente.getCnpjCpf());
               modelo.addElement(cliente.getEmail());
               modelo.addElement(cliente.getRazaoSocial());
           listbuscar.setModel(modelo);
            listbuscar.repaint();
        }

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tela_Inicial1 frame = new Tela_Inicial1();

        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listbuscarMouseClicked
        int linha = listbuscar.getSelectedIndex();
        Cliente clientes = (Cliente) vetorcliente.get(linha);
        preencheCliente(String.valueOf(clientes.getIdCliente()));
        cliente = clientes;
    }//GEN-LAST:event_listbuscarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscarCep;
    private javax.swing.JButton btneditar;
    private javax.swing.JRadioButton btnpessoafisica;
    private javax.swing.JRadioButton btnpessoajuridica;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbbairro;
    private javax.swing.JLabel lbcep;
    private javax.swing.JLabel lbcidade;
    private javax.swing.JLabel lbcomplemento;
    private javax.swing.JLabel lbestado;
    private javax.swing.JLabel lblcnpj;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblogradouro;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lbnumero;
    private javax.swing.JList<String> listbuscar;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JFormattedTextField txtcnpj;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlogradouro;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtrazaosocial;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    
            private void preencheCliente(String codigo) {
        ClienteDAO cDao = new  ClienteDAO();
        cliente = cDao.buscaCodigo(Integer.valueOf(codigo));
        txtbairro.setText(cliente.getEndereco().getBairro());
        txtcep.setText(cliente.getEndereco().getCep());
        txtcidade.setText(cliente.getEndereco().getCidade());
        txtcnpj.setText(cliente.getCnpjCpf());
        txtcod.setText(String.valueOf(cliente.getIdCliente()));
        txtcomplemento.setText(cliente.getEndereco().getComplemento());
        txtcpf.setText(cliente.getCnpjCpf());
        txtemail.setText(cliente.getEmail());
        txtlogradouro.setText(cliente.getEndereco().getLogradouro());
        txtnome.setText(cliente.getNome());
        txtnumero.setText(cliente.getEndereco().getNumero());
        txtrazaosocial.setText(cliente.getRazaoSocial());
        txttelefone.setText(cliente.getTelefone());
        }


}
