/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;



/**
 *
 * @author bieuu
 */
public class Tela_Inicial1 extends javax.swing.JFrame {
     
//    ConexaoBD conecta = new ConexaoBD();
     
    public Tela_Inicial1() {
        initComponents();
//        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        JDPPrincipal = new javax.swing.JDesktopPane();
        funcionario = new javax.swing.JLayeredPane();
        funcionario2 = new javax.swing.JLabel();
        cliente = new javax.swing.JLayeredPane();
        cliente2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        agenda = new javax.swing.JLabel();
        Dock = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        JDPPrincipal.setBackground(new java.awt.Color(240, 240, 240));
        JDPPrincipal.setForeground(new java.awt.Color(240, 240, 240));
        JDPPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcionario.setMaximumSize(new java.awt.Dimension(96, 96));
        funcionario.setMinimumSize(new java.awt.Dimension(96, 96));

        funcionario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funcionario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cliente_2.png"))); // NOI18N
        funcionario2.setMaximumSize(new java.awt.Dimension(96, 96));
        funcionario2.setMinimumSize(new java.awt.Dimension(96, 96));
        funcionario2.setPreferredSize(new java.awt.Dimension(96, 96));
        funcionario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionario2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionario2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionario2MouseExited(evt);
            }
        });

        funcionario.setLayer(funcionario2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout funcionarioLayout = new javax.swing.GroupLayout(funcionario);
        funcionario.setLayout(funcionarioLayout);
        funcionarioLayout.setHorizontalGroup(
            funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funcionario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        funcionarioLayout.setVerticalGroup(
            funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funcionarioLayout.createSequentialGroup()
                .addComponent(funcionario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JDPPrincipal.add(funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        cliente.setMaximumSize(new java.awt.Dimension(96, 96));
        cliente.setMinimumSize(new java.awt.Dimension(96, 96));

        cliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/trabalhador_1.png"))); // NOI18N
        cliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cliente2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cliente2MouseExited(evt);
            }
        });

        cliente.setLayer(cliente2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addComponent(cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JDPPrincipal.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(96, 96));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(96, 96));

        agenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png"))); // NOI18N
        agenda.setMaximumSize(new java.awt.Dimension(96, 96));
        agenda.setMinimumSize(new java.awt.Dimension(96, 96));
        agenda.setPreferredSize(new java.awt.Dimension(96, 96));
        agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agendaMouseExited(evt);
            }
        });

        jLayeredPane1.setLayer(agenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agenda, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        JDPPrincipal.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        Dock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nildo_MENU600x300.png"))); // NOI18N
        Dock.setMaximumSize(new java.awt.Dimension(96, 96));
        Dock.setMinimumSize(new java.awt.Dimension(96, 96));
        Dock.setPreferredSize(new java.awt.Dimension(96, 96));
        JDPPrincipal.add(Dock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 570, 120));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        setBounds(0, 0, 609, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionario2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionario2MouseEntered
      funcionario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cliente_1.png")));
    }//GEN-LAST:event_funcionario2MouseEntered

    private void funcionario2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionario2MouseExited
        funcionario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cliente_2.png")));
    }//GEN-LAST:event_funcionario2MouseExited

    private void funcionario2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionario2MouseClicked
        // TODO add your handling code here:
        Cadastro_funcionario frame = new Cadastro_funcionario(); 
        frame.setVisible(true);
    }//GEN-LAST:event_funcionario2MouseClicked

    private void cliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente2MouseClicked
        // TODO add your handling code here:
        Cadastro_Cliente frame = new Cadastro_Cliente(); 
        frame.setVisible(true);
    }//GEN-LAST:event_cliente2MouseClicked

    private void cliente2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente2MouseEntered
       // agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/trabalhador_2.png")));
    }//GEN-LAST:event_cliente2MouseEntered

    private void cliente2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente2MouseExited
        // TODO add your handling code here:
        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/trabalhador_1.png")));
    }//GEN-LAST:event_cliente2MouseExited

    private void agendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaMouseEntered
        // TODO add your handl
        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon2.png")));
    }//GEN-LAST:event_agendaMouseEntered

    private void agendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaMouseExited
        // TODO add your handling code here:
        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icon.png")));
    }//GEN-LAST:event_agendaMouseExited

    private void agendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaMouseClicked
        // TODO add your handling code here:
        Agenda frame = new Agenda(); 
        frame.setVisible(true);
    }//GEN-LAST:event_agendaMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dock;
    private javax.swing.JDesktopPane JDPPrincipal;
    private javax.swing.JLabel agenda;
    private javax.swing.JLayeredPane cliente;
    private javax.swing.JLabel cliente2;
    private javax.swing.JLayeredPane funcionario;
    private javax.swing.JLabel funcionario2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
